### ISSUE TITLE
How to decided endPackettimeout, queuetimeout, responsetimeout values

### ISSUE THREAD

**Issue by vishalb747** [thekip/node-modbus-rtu#5]
I want to know how we will decide endPackettimeout, queuetimeout, responsetimeout values for modbus-rtu. Is those values are depends on number of device connected in loop or depends on baudrate

**Comment by timofei-iatsenko** [comment]
Short answer: this values should be empirically selected.

Long answer:
### endPackettimeout

This is the most important timeout. This value set end of the packet.
According to modbus specifications this timeout should be fixed for each baudrate, but this is unreachable in JS, because node.js timers don't guarantee execution in exact time, furthermore such small timeouts (<4ms), can not be achieved.

From readme: 
>If you set **too small timeout** worker will incorrect collect buffers and you will often receive CRC error.
>If you set **too big timeout** communication will be very slow.

So try to set this value as small as possible until you see the CRC errors.

### responseTimeout
This value set how long library will be wait answer from slave before return `Timeout error`

If all your devices is fast, and answer quite fast, you can set this value to 100ms (or choose empirically for you devices). 

In my case, I have Chinese thermostats which some times answer immediately, some times with 500ms delay, sometimes don't answer at all. 

So we need  this timeout to terminate this "unanswered" calls.

###  queueTimeout
This value set how long will be pause between calls in queue. And actually you don't have to change it (I don't remember that I had to change this).
But again you can set it as small as possible until system became unstable.
